language: ruby
rvm:
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate db:test:prepare spec cucumber
before_script:
  - cp config/database.yml.travis config/database.yml
